# -*- coding: utf-8 -*-
"""Aula2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LYO_lLAVGXVwOo7P7MkhrSwR_7Exf1ND
"""

#import das bibliotecas pandas e numpy

import numpy as np
import pandas as pd

dados = pd.read_csv('/content/drive/MyDrive/Estatistica/CotacoesMoedasPeriodo.csv', sep = ';', header= None)

dados.head(5)

dados.tail(5)

dados.shape
#23 linhas e 8 colunas

dados.columns = ['datas', 'codigo', 'tipo', 'simbolo', 'compra', 'venda', 'ns1', 'ns2']

dados.head()

dados = dados.rename(columns={'ns1': 'n10'})

dados.head()

dados1 = dados.drop(columns=['n10', 'ns2'])
dados1.head(2)

"""Análise dos tipos de atributos:

object: strings

int64: inteiros

float64: reais

complex: complexos
"""

dados1.dtypes

dados1['datas'] = dados1['datas'].astype(str).str.zfill(8)
dados1['datas'] = pd.to_datetime(dados1['datas'], format='%d%m%Y')
dados1['datas'] = dados1['datas'].dt.strftime('%d/%m/%Y')
dados1.head()

dados1['datas'].dtypes

dados1['compra'] = dados1['compra'].apply(lambda x: x.replace(',','.'))
dados1['venda'] = dados1['venda'].apply(lambda x: x.replace(',','.'))
dados1.head()
#substitui , por . em ['compra'] e ['venda']

dados1['compra'] = dados1['compra'].astype(float)
dados1['venda'] = dados1['venda'].astype(float)
dados1.head()

dados1.dtypes

dados1.to_csv('dados_tratados.csv', index=False)

dados1.to_csv('/content/drive/MyDrive/Estatistica/CotacoesMoedasPeriodo.csv', index = False)